version: '3.9'
services:
  nuxt:
    image: node:16.14.0-bullseye
    ports:
      - 3000:3000
    volumes:
      - ./:/masher_nuxt
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  redis:
    image: redis:7.0.0-bullseye
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
